-- Insert Melville plumbers
INSERT INTO plumbers (name, slug, phone, email, address, suburb, rating, review_count, services, description, business_hours, emergency_available, years_experience, license_number, website) VALUES
('AquaFlow Plumbing', 'aquaflow-plumbing', '(08) 9330 1234', 'info@aquaflow.com.au', '123 Canning Highway, Melville WA 6156', 'Melville', 4.8, 127, ARRAY['Blocked Drains', 'Hot Water Systems', 'Leak Detection', 'General Plumbing'], 'Professional plumbing services with over 15 years of experience in the Melville area. We pride ourselves on quality workmanship and reliable service.', '{"monday": "7:00 AM - 6:00 PM", "tuesday": "7:00 AM - 6:00 PM", "wednesday": "7:00 AM - 6:00 PM", "thursday": "7:00 AM - 6:00 PM", "friday": "7:00 AM - 6:00 PM", "saturday": "8:00 AM - 4:00 PM", "sunday": "Emergency only"}', true, 15, 'PL8901', 'www.aquaflow.com.au'),

('Melville Drain Masters', 'melville-drain-masters', '(08) 9330 5678', 'contact@drainmasters.com.au', '456 Leach Highway, Melville WA 6156', 'Melville', 4.6, 89, ARRAY['Blocked Drains', 'CCTV Inspections', 'Pipe Relining', 'Emergency Plumbing'], 'Specialists in drain cleaning and pipe repairs. Fast, efficient service with modern equipment and techniques.', '{"monday": "6:00 AM - 8:00 PM", "tuesday": "6:00 AM - 8:00 PM", "wednesday": "6:00 AM - 8:00 PM", "thursday": "6:00 AM - 8:00 PM", "friday": "6:00 AM - 8:00 PM", "saturday": "7:00 AM - 5:00 PM", "sunday": "8:00 AM - 4:00 PM"}', true, 12, 'PL7234', 'www.drainmasters.com.au'),

('Swan River Plumbing Co.', 'swan-river-plumbing', '(08) 9330 9012', 'hello@swanriverplumbing.com.au', '789 Stock Road, Melville WA 6156', 'Melville', 4.9, 156, ARRAY['Hot Water Systems', 'Bathroom Renovations', 'General Plumbing', 'Gas Fitting'], 'Family-owned business serving Melville for over 20 years. Complete plumbing solutions from repairs to full renovations.', '{"monday": "7:30 AM - 5:30 PM", "tuesday": "7:30 AM - 5:30 PM", "wednesday": "7:30 AM - 5:30 PM", "thursday": "7:30 AM - 5:30 PM", "friday": "7:30 AM - 5:30 PM", "saturday": "8:00 AM - 2:00 PM", "sunday": "Closed"}', false, 20, 'PL5567', 'www.swanriverplumbing.com.au'),

('Rapid Response Plumbers', 'rapid-response-plumbers', '(08) 9330 3456', 'urgent@rapidresponse.com.au', '321 Marmion Street, Melville WA 6156', 'Melville', 4.7, 203, ARRAY['Emergency Plumbing', 'Leak Detection', 'Pipe Repairs', 'Hot Water Systems'], '24/7 emergency plumbing service. When you need help fast, we''re here. Fully licensed and insured with rapid response times.', '{"monday": "24 hours", "tuesday": "24 hours", "wednesday": "24 hours", "thursday": "24 hours", "friday": "24 hours", "saturday": "24 hours", "sunday": "24 hours"}', true, 8, 'PL9876', 'www.rapidresponse.com.au'),

('Melville Hot Water Experts', 'melville-hot-water-experts', '(08) 9330 7890', 'service@hotwater.com.au', '654 Riseley Street, Melville WA 6156', 'Melville', 4.5, 74, ARRAY['Hot Water Systems', 'Solar Hot Water', 'Gas Fitting', 'General Plumbing'], 'Specialists in hot water system installation, repair, and maintenance. We work with all major brands and offer energy-efficient solutions.', '{"monday": "8:00 AM - 5:00 PM", "tuesday": "8:00 AM - 5:00 PM", "wednesday": "8:00 AM - 5:00 PM", "thursday": "8:00 AM - 5:00 PM", "friday": "8:00 AM - 5:00 PM", "saturday": "9:00 AM - 1:00 PM", "sunday": "Closed"}', false, 18, 'PL4321', 'www.hotwater.com.au'),

('ProFix Plumbing Services', 'profix-plumbing', '(08) 9330 2468', 'info@profix.com.au', '987 Applecross Road, Melville WA 6156', 'Melville', 4.4, 92, ARRAY['General Plumbing', 'Bathroom Renovations', 'Leak Detection', 'Pipe Repairs'], 'Reliable plumbing services for residential and commercial properties. Quality workmanship at competitive prices.', '{"monday": "7:00 AM - 6:00 PM", "tuesday": "7:00 AM - 6:00 PM", "wednesday": "7:00 AM - 6:00 PM", "thursday": "7:00 AM - 6:00 PM", "friday": "7:00 AM - 6:00 PM", "saturday": "8:00 AM - 4:00 PM", "sunday": "Emergency only"}', true, 10, 'PL1357', 'www.profix.com.au'),

('Eco Plumbing Solutions', 'eco-plumbing-solutions', '(08) 9330 1357', 'green@ecoplumbing.com.au', '147 Melville Parade, Melville WA 6156', 'Melville', 4.6, 68, ARRAY['Solar Hot Water', 'Water Efficiency', 'General Plumbing', 'Rainwater Systems'], 'Environmentally conscious plumbing solutions. Specializing in water-saving technologies and sustainable plumbing practices.', '{"monday": "8:00 AM - 5:00 PM", "tuesday": "8:00 AM - 5:00 PM", "wednesday": "8:00 AM - 5:00 PM", "thursday": "8:00 AM - 5:00 PM", "friday": "8:00 AM - 5:00 PM", "saturday": "9:00 AM - 2:00 PM", "sunday": "Closed"}', false, 7, 'PL2468', 'www.ecoplumbing.com.au'),

('All Hours Plumbing', 'all-hours-plumbing', '(08) 9330 8024', 'help@allhours.com.au', '258 Petra Street, Melville WA 6156', 'Melville', 4.3, 115, ARRAY['Emergency Plumbing', 'Blocked Drains', 'General Plumbing', 'Hot Water Systems'], 'Round-the-clock plumbing services for all your urgent needs. No job too big or small, available 24/7 for emergencies.', '{"monday": "24 hours", "tuesday": "24 hours", "wednesday": "24 hours", "thursday": "24 hours", "friday": "24 hours", "saturday": "24 hours", "sunday": "24 hours"}', true, 14, 'PL3691', 'www.allhours.com.au');

-- Insert Myaree plumbers
INSERT INTO plumbers (name, slug, phone, email, address, suburb, rating, review_count, services, description, business_hours, emergency_available, years_experience, license_number, website) VALUES
('Myaree Drain Solutions', 'myaree-drain-solutions', '(08) 9330 4567', 'info@myareedrain.com.au', '123 North Lake Road, Myaree WA 6154', 'Myaree', 4.7, 94, ARRAY['Blocked Drains', 'CCTV Inspections', 'High Pressure Cleaning', 'Pipe Repairs'], 'Expert drain cleaning and repair services in Myaree. Using the latest technology to solve your drainage problems quickly and efficiently.', '{"monday": "7:00 AM - 6:00 PM", "tuesday": "7:00 AM - 6:00 PM", "wednesday": "7:00 AM - 6:00 PM", "thursday": "7:00 AM - 6:00 PM", "friday": "7:00 AM - 6:00 PM", "saturday": "8:00 AM - 4:00 PM", "sunday": "Emergency only"}', true, 11, 'PL5678', 'www.myareedrain.com.au'),

('South Perth Plumbing', 'south-perth-plumbing', '(08) 9330 8901', 'contact@southperthplumbing.com.au', '456 Marmion Street, Myaree WA 6154', 'Myaree', 4.8, 142, ARRAY['General Plumbing', 'Hot Water Systems', 'Bathroom Renovations', 'Gas Fitting'], 'Comprehensive plumbing services for Myaree and surrounding areas. Professional, reliable, and competitively priced.', '{"monday": "7:30 AM - 5:30 PM", "tuesday": "7:30 AM - 5:30 PM", "wednesday": "7:30 AM - 5:30 PM", "thursday": "7:30 AM - 5:30 PM", "friday": "7:30 AM - 5:30 PM", "saturday": "8:00 AM - 3:00 PM", "sunday": "Closed"}', false, 16, 'PL9012', 'www.southperthplumbing.com.au'),

('Emergency Plumbers Myaree', 'emergency-plumbers-myaree', '(08) 9330 2345', 'urgent@emergencyplumbers.com.au', '789 Leach Highway, Myaree WA 6154', 'Myaree', 4.5, 87, ARRAY['Emergency Plumbing', 'Burst Pipes', 'Leak Detection', 'Hot Water Systems'], '24/7 emergency plumbing service in Myaree. Fast response times and quality repairs when you need them most.', '{"monday": "24 hours", "tuesday": "24 hours", "wednesday": "24 hours", "thursday": "24 hours", "friday": "24 hours", "saturday": "24 hours", "sunday": "24 hours"}', true, 9, 'PL3456', 'www.emergencyplumbers.com.au'),

('Myaree Hot Water Specialists', 'myaree-hot-water-specialists', '(08) 9330 6789', 'service@myareehotwater.com.au', '321 Riseley Street, Myaree WA 6154', 'Myaree', 4.6, 76, ARRAY['Hot Water Systems', 'Solar Hot Water', 'Heat Pumps', 'Gas Fitting'], 'Hot water system experts serving Myaree. Installation, repair, and maintenance of all types of hot water systems.', '{"monday": "8:00 AM - 5:00 PM", "tuesday": "8:00 AM - 5:00 PM", "wednesday": "8:00 AM - 5:00 PM", "thursday": "8:00 AM - 5:00 PM", "friday": "8:00 AM - 5:00 PM", "saturday": "9:00 AM - 2:00 PM", "sunday": "Closed"}', false, 13, 'PL6789', 'www.myareehotwater.com.au'),

('Reliable Plumbing Co.', 'reliable-plumbing-co', '(08) 9330 1098', 'hello@reliableplumbing.com.au', '654 Stock Road, Myaree WA 6154', 'Myaree', 4.4, 103, ARRAY['General Plumbing', 'Bathroom Renovations', 'Leak Detection', 'Pipe Repairs'], 'Trusted plumbing services in Myaree. Family business with a focus on honest, reliable service and fair pricing.', '{"monday": "7:00 AM - 6:00 PM", "tuesday": "7:00 AM - 6:00 PM", "wednesday": "7:00 AM - 6:00 PM", "thursday": "7:00 AM - 6:00 PM", "friday": "7:00 AM - 6:00 PM", "saturday": "8:00 AM - 4:00 PM", "sunday": "Emergency only"}', true, 12, 'PL0987', 'www.reliableplumbing.com.au'),

('Green Plumbing Myaree', 'green-plumbing-myaree', '(08) 9330 5432', 'eco@greenplumbing.com.au', '987 Applecross Road, Myaree WA 6154', 'Myaree', 4.7, 59, ARRAY['Water Efficiency', 'Solar Hot Water', 'Rainwater Systems', 'General Plumbing'], 'Eco-friendly plumbing solutions for environmentally conscious customers. Specializing in water conservation and sustainable practices.', '{"monday": "8:00 AM - 5:00 PM", "tuesday": "8:00 AM - 5:00 PM", "wednesday": "8:00 AM - 5:00 PM", "thursday": "8:00 AM - 5:00 PM", "friday": "8:00 AM - 5:00 PM", "saturday": "9:00 AM - 1:00 PM", "sunday": "Closed"}', false, 8, 'PL5432', 'www.greenplumbing.com.au');
