-- Clear existing data and seed all plumbers
TRUNCATE TABLE plumbers RESTART IDENTITY CASCADE;

-- Insert all 14 plumbers with complete data
INSERT INTO plumbers (
  name, slug, phone, email, address, suburb, rating, review_count, 
  services, description, emergency_available, business_hours, reviews, hero_image
) VALUES 
-- Melville Plumbers
(
  '24/7 Plumbing Melville',
  '24-7-plumbing-melville',
  '(08) 9364 2247',
  'info@247plumbingmelville.com.au',
  '123 Canning Highway, Melville WA 6156',
  'Melville',
  4.8,
  127,
  ARRAY['Emergency Repairs', 'Blocked Drains', 'Hot Water Systems', 'Leak Detection'],
  'Available 24/7 for all your emergency plumbing needs in Melville and surrounding areas.',
  true,
  '{"Monday": "24 hours", "Tuesday": "24 hours", "Wednesday": "24 hours", "Thursday": "24 hours", "Friday": "24 hours", "Saturday": "24 hours", "Sunday": "24 hours"}'::jsonb,
  '[{"author": "Sarah M.", "rating": 5, "comment": "Excellent emergency service! Fixed our burst pipe at 2am."}, {"author": "David L.", "rating": 5, "comment": "Professional and reliable. Highly recommend for any plumbing emergency."}, {"author": "Emma K.", "rating": 4, "comment": "Quick response time and fair pricing."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Melville Master Plumbers',
  'melville-master-plumbers',
  '(08) 9330 1234',
  'contact@melvillemasterplumbers.com.au',
  '456 Leach Highway, Melville WA 6156',
  'Melville',
  4.9,
  203,
  ARRAY['Bathroom Renovations', 'Kitchen Plumbing', 'Gas Fitting', 'Pipe Relining'],
  'Master plumbers with over 20 years experience in residential and commercial plumbing.',
  false,
  '{"Monday": "7:00 AM - 5:00 PM", "Tuesday": "7:00 AM - 5:00 PM", "Wednesday": "7:00 AM - 5:00 PM", "Thursday": "7:00 AM - 5:00 PM", "Friday": "7:00 AM - 5:00 PM", "Saturday": "8:00 AM - 2:00 PM", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Michael R.", "rating": 5, "comment": "Outstanding bathroom renovation. Attention to detail was exceptional."}, {"author": "Lisa T.", "rating": 5, "comment": "Professional team, quality workmanship, completed on time."}, {"author": "James W.", "rating": 5, "comment": "Best plumbers in Melville! Highly skilled and reliable."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'AquaFlow Plumbing',
  'aquaflow-plumbing',
  '(08) 9364 5678',
  'hello@aquaflowplumbing.com.au',
  '789 Stock Road, Melville WA 6156',
  'Melville',
  4.7,
  156,
  ARRAY['Hot Water Systems', 'Leak Detection', 'Tap Repairs', 'Toilet Repairs'],
  'Specializing in water system repairs and installations with eco-friendly solutions.',
  true,
  '{"Monday": "6:00 AM - 6:00 PM", "Tuesday": "6:00 AM - 6:00 PM", "Wednesday": "6:00 AM - 6:00 PM", "Thursday": "6:00 AM - 6:00 PM", "Friday": "6:00 AM - 6:00 PM", "Saturday": "8:00 AM - 4:00 PM", "Sunday": "Emergency only"}'::jsonb,
  '[{"author": "Rachel P.", "rating": 5, "comment": "Fixed our hot water system quickly and efficiently."}, {"author": "Tom H.", "rating": 4, "comment": "Great service, very knowledgeable about eco-friendly options."}, {"author": "Anna S.", "rating": 5, "comment": "Reliable and honest pricing. Will use again."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Reliable Drain Solutions',
  'reliable-drain-solutions',
  '(08) 9330 9876',
  'info@reliabledrains.com.au',
  '321 Riseley Street, Melville WA 6156',
  'Melville',
  4.6,
  89,
  ARRAY['Blocked Drains', 'CCTV Inspections', 'Pipe Relining', 'Stormwater'],
  'Drain specialists using the latest technology for accurate diagnosis and repair.',
  false,
  '{"Monday": "7:30 AM - 4:30 PM", "Tuesday": "7:30 AM - 4:30 PM", "Wednesday": "7:30 AM - 4:30 PM", "Thursday": "7:30 AM - 4:30 PM", "Friday": "7:30 AM - 4:30 PM", "Saturday": "Closed", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Peter K.", "rating": 5, "comment": "CCTV inspection revealed the exact problem. Professional service."}, {"author": "Helen M.", "rating": 4, "comment": "Cleared our blocked drain efficiently."}, {"author": "Chris B.", "rating": 5, "comment": "Excellent pipe relining work. No more root problems!"}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Perth Gas & Plumbing',
  'perth-gas-plumbing',
  '(08) 9364 4321',
  'service@perthgasplumbing.com.au',
  '654 Marmion Street, Melville WA 6156',
  'Melville',
  4.8,
  174,
  ARRAY['Gas Fitting', 'Hot Water Systems', 'Heating Systems', 'Appliance Installation'],
  'Licensed gas fitters and plumbers for all your heating and hot water needs.',
  true,
  '{"Monday": "7:00 AM - 5:30 PM", "Tuesday": "7:00 AM - 5:30 PM", "Wednesday": "7:00 AM - 5:30 PM", "Thursday": "7:00 AM - 5:30 PM", "Friday": "7:00 AM - 5:30 PM", "Saturday": "8:00 AM - 1:00 PM", "Sunday": "Emergency only"}'::jsonb,
  '[{"author": "Mark D.", "rating": 5, "comment": "Professional gas fitting service. Safety is clearly their priority."}, {"author": "Jenny L.", "rating": 5, "comment": "Installed our new heating system perfectly."}, {"author": "Robert F.", "rating": 4, "comment": "Reliable and experienced team."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Swan River Plumbing',
  'swan-river-plumbing',
  '(08) 9330 7890',
  'contact@swanriverplumbing.com.au',
  '987 Preston Point Road, Melville WA 6156',
  'Melville',
  4.5,
  112,
  ARRAY['General Plumbing', 'Maintenance', 'Renovations', 'Commercial'],
  'Full-service plumbing for residential and commercial properties along the Swan River.',
  false,
  '{"Monday": "8:00 AM - 4:00 PM", "Tuesday": "8:00 AM - 4:00 PM", "Wednesday": "8:00 AM - 4:00 PM", "Thursday": "8:00 AM - 4:00 PM", "Friday": "8:00 AM - 4:00 PM", "Saturday": "Closed", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Susan W.", "rating": 4, "comment": "Good general plumbing service. Reasonable rates."}, {"author": "Andrew T.", "rating": 5, "comment": "Handled our commercial plumbing needs professionally."}, {"author": "Maria G.", "rating": 4, "comment": "Reliable for maintenance work."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Elite Emergency Plumbers',
  'elite-emergency-plumbers',
  '(08) 9364 1111',
  'emergency@eliteplumbers.com.au',
  '159 Melville Parade, Melville WA 6156',
  'Melville',
  4.9,
  245,
  ARRAY['Emergency Repairs', 'Burst Pipes', 'Blocked Drains', 'Hot Water Systems'],
  'Elite emergency plumbing service with guaranteed 30-minute response time.',
  true,
  '{"Monday": "24 hours", "Tuesday": "24 hours", "Wednesday": "24 hours", "Thursday": "24 hours", "Friday": "24 hours", "Saturday": "24 hours", "Sunday": "24 hours"}'::jsonb,
  '[{"author": "Karen J.", "rating": 5, "comment": "True to their word - 25 minute response time for our burst pipe!"}, {"author": "Steve M.", "rating": 5, "comment": "Elite service indeed. Professional and fast."}, {"author": "Linda R.", "rating": 5, "comment": "Best emergency plumbers in Perth. Saved our weekend!"}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Melville Maintenance Plumbing',
  'melville-maintenance-plumbing',
  '(08) 9330 5555',
  'info@melvillemaintenance.com.au',
  '753 Canning Highway, Melville WA 6156',
  'Melville',
  4.4,
  67,
  ARRAY['Maintenance', 'Tap Repairs', 'Toilet Repairs', 'General Plumbing'],
  'Affordable maintenance plumbing services for homes and small businesses.',
  false,
  '{"Monday": "9:00 AM - 3:00 PM", "Tuesday": "9:00 AM - 3:00 PM", "Wednesday": "9:00 AM - 3:00 PM", "Thursday": "9:00 AM - 3:00 PM", "Friday": "9:00 AM - 3:00 PM", "Saturday": "Closed", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Paul N.", "rating": 4, "comment": "Good value for basic plumbing repairs."}, {"author": "Michelle K.", "rating": 4, "comment": "Fixed our leaky taps efficiently."}, {"author": "Tony B.", "rating": 5, "comment": "Honest pricing and reliable service."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),

-- Myaree Plumbers
(
  'Myaree Drain Solutions',
  'myaree-drain-solutions',
  '(08) 9330 2468',
  'help@myareedrains.com.au',
  '123 South Street, Myaree WA 6154',
  'Myaree',
  4.7,
  134,
  ARRAY['Blocked Drains', 'CCTV Inspections', 'High Pressure Cleaning', 'Pipe Repairs'],
  'Myaree''s drain specialists with advanced equipment for all drainage problems.',
  true,
  '{"Monday": "6:00 AM - 6:00 PM", "Tuesday": "6:00 AM - 6:00 PM", "Wednesday": "6:00 AM - 6:00 PM", "Thursday": "6:00 AM - 6:00 PM", "Friday": "6:00 AM - 6:00 PM", "Saturday": "7:00 AM - 3:00 PM", "Sunday": "Emergency only"}'::jsonb,
  '[{"author": "Nicole H.", "rating": 5, "comment": "Cleared our stubborn blockage with high pressure cleaning."}, {"author": "Greg S.", "rating": 4, "comment": "Professional CCTV inspection service."}, {"author": "Amanda L.", "rating": 5, "comment": "Fast response for emergency drain issues."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'South Street Plumbing',
  'south-street-plumbing',
  '(08) 9364 8642',
  'info@southstreetplumbing.com.au',
  '456 South Street, Myaree WA 6154',
  'Myaree',
  4.6,
  98,
  ARRAY['General Plumbing', 'Hot Water Systems', 'Bathroom Renovations', 'Leak Detection'],
  'Comprehensive plumbing services for Myaree residents and businesses.',
  false,
  '{"Monday": "7:00 AM - 4:00 PM", "Tuesday": "7:00 AM - 4:00 PM", "Wednesday": "7:00 AM - 4:00 PM", "Thursday": "7:00 AM - 4:00 PM", "Friday": "7:00 AM - 4:00 PM", "Saturday": "8:00 AM - 12:00 PM", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Brian C.", "rating": 5, "comment": "Excellent bathroom renovation work."}, {"author": "Fiona M.", "rating": 4, "comment": "Reliable hot water system installation."}, {"author": "Daniel P.", "rating": 4, "comment": "Good general plumbing service."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Rapid Response Plumbing Myaree',
  'rapid-response-plumbing-myaree',
  '(08) 9330 9753',
  'rapid@rapidplumbingmyaree.com.au',
  '789 Leach Highway, Myaree WA 6154',
  'Myaree',
  4.8,
  167,
  ARRAY['Emergency Repairs', 'Burst Pipes', 'Gas Leaks', 'Hot Water Systems'],
  'Rapid emergency response plumbing service covering Myaree and surrounding suburbs.',
  true,
  '{"Monday": "24 hours", "Tuesday": "24 hours", "Wednesday": "24 hours", "Thursday": "24 hours", "Friday": "24 hours", "Saturday": "24 hours", "Sunday": "24 hours"}'::jsonb,
  '[{"author": "Catherine R.", "rating": 5, "comment": "Incredibly fast response to our gas leak emergency."}, {"author": "Matthew W.", "rating": 5, "comment": "Professional emergency service, highly recommended."}, {"author": "Sarah D.", "rating": 4, "comment": "Quick burst pipe repair, minimal disruption."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Myaree Hot Water Specialists',
  'myaree-hot-water-specialists',
  '(08) 9364 3691',
  'service@myareehotwater.com.au',
  '321 North Lake Road, Myaree WA 6154',
  'Myaree',
  4.9,
  189,
  ARRAY['Hot Water Systems', 'Solar Hot Water', 'Heat Pumps', 'Gas Systems'],
  'Hot water system specialists with expertise in solar and energy-efficient solutions.',
  false,
  '{"Monday": "7:30 AM - 5:00 PM", "Tuesday": "7:30 AM - 5:00 PM", "Wednesday": "7:30 AM - 5:00 PM", "Thursday": "7:30 AM - 5:00 PM", "Friday": "7:30 AM - 5:00 PM", "Saturday": "8:00 AM - 2:00 PM", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Jennifer L.", "rating": 5, "comment": "Excellent solar hot water installation. Very knowledgeable."}, {"author": "Kevin T.", "rating": 5, "comment": "Heat pump installation was flawless. Great energy savings!"}, {"author": "Rebecca M.", "rating": 5, "comment": "Best hot water specialists in the area."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Garden City Plumbing Services',
  'garden-city-plumbing-services',
  '(08) 9330 1597',
  'contact@gardencityplumbing.com.au',
  '654 Riseley Street, Myaree WA 6154',
  'Myaree',
  4.5,
  76,
  ARRAY['General Plumbing', 'Maintenance', 'Tap Repairs', 'Toilet Repairs'],
  'Friendly local plumbing service for Garden City and Myaree area residents.',
  false,
  '{"Monday": "8:00 AM - 4:30 PM", "Tuesday": "8:00 AM - 4:30 PM", "Wednesday": "8:00 AM - 4:30 PM", "Thursday": "8:00 AM - 4:30 PM", "Friday": "8:00 AM - 4:30 PM", "Saturday": "Closed", "Sunday": "Closed"}'::jsonb,
  '[{"author": "Patricia S.", "rating": 4, "comment": "Friendly service, fixed our toilet issues promptly."}, {"author": "John M.", "rating": 5, "comment": "Local plumber who really cares about the community."}, {"author": "Mary K.", "rating": 4, "comment": "Reliable maintenance service."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
),
(
  'Professional Plumbing Myaree',
  'professional-plumbing-myaree',
  '(08) 9364 7531',
  'admin@professionalplumbingmyaree.com.au',
  '987 Marmion Street, Myaree WA 6154',
  'Myaree',
  4.7,
  143,
  ARRAY['Commercial Plumbing', 'Renovations', 'Gas Fitting', 'Maintenance'],
  'Professional plumbing services specializing in commercial and residential projects.',
  true,
  '{"Monday": "6:30 AM - 6:00 PM", "Tuesday": "6:30 AM - 6:00 PM", "Wednesday": "6:30 AM - 6:00 PM", "Thursday": "6:30 AM - 6:00 PM", "Friday": "6:30 AM - 6:00 PM", "Saturday": "7:00 AM - 2:00 PM", "Sunday": "Emergency only"}'::jsonb,
  '[{"author": "Richard B.", "rating": 5, "comment": "Excellent commercial plumbing work for our office building."}, {"author": "Lisa H.", "rating": 4, "comment": "Professional renovation plumbing service."}, {"author": "Michael S.", "rating": 5, "comment": "Reliable and professional team."}]'::jsonb,
  '/placeholder.svg?height=400&width=800'
);
