-- Clear existing data and insert complete plumber dataset with hero images
TRUNCATE TABLE plumbers RESTART IDENTITY CASCADE;

INSERT INTO plumbers (
  name, slug, phone, email, address, suburb, description, services, 
  rating, review_count, emergency_available, years_experience, 
  license_number, website, business_hours, hero_image
) VALUES 
-- Melville Plumbers
('24/7 Plumbing Melville', '24-7-plumbing-melville', '(08) 9364 2247', 'info@247plumbingmelville.com.au', '123 Canning Highway, Melville WA 6156', 'Melville', 'Emergency plumbing services available 24/7 in Melville and surrounding areas. Fast, reliable, and professional service for all your plumbing needs.', ARRAY['Emergency Repairs', 'Blocked Drains', 'Hot Water Systems', 'Leak Detection', 'Pipe Relining'], 4.8, 127, true, 15, 'PL8901', 'https://247plumbingmelville.com.au', '{"Monday": "24 Hours", "Tuesday": "24 Hours", "Wednesday": "24 Hours", "Thursday": "24 Hours", "Friday": "24 Hours", "Saturday": "24 Hours", "Sunday": "24 Hours"}', '/placeholder.svg?height=400&width=800'),

('AquaFlow Plumbing', 'aquaflow-plumbing', '(08) 9364 1234', 'contact@aquaflowplumbing.com.au', '456 Leach Highway, Melville WA 6156', 'Melville', 'Specializing in modern plumbing solutions with eco-friendly approaches. Quality workmanship guaranteed for residential and commercial properties.', ARRAY['Bathroom Renovations', 'Kitchen Plumbing', 'Gas Fitting', 'Backflow Prevention', 'Water Efficiency'], 4.6, 89, false, 12, 'PL7234', 'https://aquaflowplumbing.com.au', '{"Monday": "7:00 AM - 5:00 PM", "Tuesday": "7:00 AM - 5:00 PM", "Wednesday": "7:00 AM - 5:00 PM", "Thursday": "7:00 AM - 5:00 PM", "Friday": "7:00 AM - 5:00 PM", "Saturday": "8:00 AM - 2:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Melville Drain Masters', 'melville-drain-masters', '(08) 9364 5678', 'service@melvilledrainmasters.com.au', '789 Stock Road, Melville WA 6156', 'Melville', 'Drain cleaning specialists with advanced CCTV inspection technology. We solve the toughest blockages and provide permanent solutions.', ARRAY['Drain Cleaning', 'CCTV Inspections', 'High Pressure Jetting', 'Root Removal', 'Pipe Repairs'], 4.7, 156, true, 18, 'PL6789', 'https://melvilledrainmasters.com.au', '{"Monday": "6:00 AM - 6:00 PM", "Tuesday": "6:00 AM - 6:00 PM", "Wednesday": "6:00 AM - 6:00 PM", "Thursday": "6:00 AM - 6:00 PM", "Friday": "6:00 AM - 6:00 PM", "Saturday": "7:00 AM - 4:00 PM", "Sunday": "8:00 AM - 2:00 PM"}', '/placeholder.svg?height=400&width=800'),

('Perth Hot Water Pros', 'perth-hot-water-pros', '(08) 9364 9012', 'info@perthhotwaterpros.com.au', '321 Riseley Street, Melville WA 6156', 'Melville', 'Hot water system specialists serving Perth metro area. Installation, repair, and maintenance of all major brands with same-day service available.', ARRAY['Hot Water Installation', 'System Repairs', 'Gas Hot Water', 'Electric Hot Water', 'Solar Hot Water'], 4.9, 203, true, 20, 'PL5432', 'https://perthhotwaterpros.com.au', '{"Monday": "7:00 AM - 7:00 PM", "Tuesday": "7:00 AM - 7:00 PM", "Wednesday": "7:00 AM - 7:00 PM", "Thursday": "7:00 AM - 7:00 PM", "Friday": "7:00 AM - 7:00 PM", "Saturday": "8:00 AM - 5:00 PM", "Sunday": "9:00 AM - 3:00 PM"}', '/placeholder.svg?height=400&width=800'),

('Reliable Plumbing Melville', 'reliable-plumbing-melville', '(08) 9364 3456', 'hello@reliableplumbingmelville.com.au', '654 Canning Highway, Melville WA 6156', 'Melville', 'Family-owned plumbing business providing honest, reliable service to Melville residents for over two decades. No job too big or small.', ARRAY['General Plumbing', 'Tap Repairs', 'Toilet Repairs', 'Pipe Repairs', 'Maintenance'], 4.5, 178, false, 22, 'PL4321', 'https://reliableplumbingmelville.com.au', '{"Monday": "8:00 AM - 4:30 PM", "Tuesday": "8:00 AM - 4:30 PM", "Wednesday": "8:00 AM - 4:30 PM", "Thursday": "8:00 AM - 4:30 PM", "Friday": "8:00 AM - 4:30 PM", "Saturday": "Closed", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Swan River Plumbing', 'swan-river-plumbing', '(08) 9364 7890', 'contact@swanriverplumbing.com.au', '987 Preston Point Road, Melville WA 6156', 'Melville', 'Commercial and residential plumbing services with a focus on sustainable solutions. Fully licensed and insured with competitive pricing.', ARRAY['Commercial Plumbing', 'Residential Plumbing', 'Maintenance Contracts', 'Water Saving Solutions', 'Compliance Inspections'], 4.4, 92, false, 14, 'PL3210', 'https://swanriverplumbing.com.au', '{"Monday": "7:30 AM - 4:00 PM", "Tuesday": "7:30 AM - 4:00 PM", "Wednesday": "7:30 AM - 4:00 PM", "Thursday": "7:30 AM - 4:00 PM", "Friday": "7:30 AM - 4:00 PM", "Saturday": "Closed", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Elite Emergency Plumbers', 'elite-emergency-plumbers', '(08) 9364 2468', 'emergency@eliteplumbers.com.au', '147 Melville Parade, Melville WA 6156', 'Melville', 'Premium emergency plumbing service with guaranteed 30-minute response time. Available 24/7 for urgent plumbing emergencies across Perth metro.', ARRAY['Emergency Repairs', 'Burst Pipes', 'Gas Leaks', 'Sewer Blockages', 'Flood Damage'], 4.8, 134, true, 16, 'PL2109', 'https://eliteplumbers.com.au', '{"Monday": "24 Hours", "Tuesday": "24 Hours", "Wednesday": "24 Hours", "Thursday": "24 Hours", "Friday": "24 Hours", "Saturday": "24 Hours", "Sunday": "24 Hours"}', '/placeholder.svg?height=400&width=800'),

('Melville Bathroom Specialists', 'melville-bathroom-specialists', '(08) 9364 1357', 'info@melvillebathrooms.com.au', '258 Kintail Road, Melville WA 6156', 'Melville', 'Complete bathroom renovation specialists combining plumbing expertise with design flair. Transform your bathroom with our end-to-end service.', ARRAY['Bathroom Renovations', 'Vanity Installation', 'Shower Installation', 'Toilet Installation', 'Tile Work'], 4.7, 67, false, 11, 'PL1098', 'https://melvillebathrooms.com.au', '{"Monday": "8:00 AM - 5:00 PM", "Tuesday": "8:00 AM - 5:00 PM", "Wednesday": "8:00 AM - 5:00 PM", "Thursday": "8:00 AM - 5:00 PM", "Friday": "8:00 AM - 5:00 PM", "Saturday": "9:00 AM - 1:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

-- Myaree Plumbers
('Myaree Plumbing Solutions', 'myaree-plumbing-solutions', '(08) 9330 1234', 'info@myareeplumbing.com.au', '123 North Lake Road, Myaree WA 6154', 'Myaree', 'Local Myaree plumbers providing comprehensive plumbing services to residential and commercial clients. Quality work at fair prices.', ARRAY['General Plumbing', 'Hot Water Systems', 'Blocked Drains', 'Leak Detection', 'Gas Fitting'], 4.6, 98, true, 13, 'PL9876', 'https://myareeplumbing.com.au', '{"Monday": "7:00 AM - 5:00 PM", "Tuesday": "7:00 AM - 5:00 PM", "Wednesday": "7:00 AM - 5:00 PM", "Thursday": "7:00 AM - 5:00 PM", "Friday": "7:00 AM - 5:00 PM", "Saturday": "8:00 AM - 3:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('South Perth Drain Experts', 'south-perth-drain-experts', '(08) 9330 5678', 'service@southperthdrains.com.au', '456 Marmion Street, Myaree WA 6154', 'Myaree', 'Drain specialists serving South Perth region with advanced equipment and techniques. Fast resolution of all drainage problems.', ARRAY['Drain Cleaning', 'Pipe Relining', 'CCTV Inspections', 'Excavation', 'Stormwater'], 4.5, 112, false, 17, 'PL8765', 'https://southperthdrains.com.au', '{"Monday": "6:30 AM - 5:30 PM", "Tuesday": "6:30 AM - 5:30 PM", "Wednesday": "6:30 AM - 5:30 PM", "Thursday": "6:30 AM - 5:30 PM", "Friday": "6:30 AM - 5:30 PM", "Saturday": "7:00 AM - 3:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Myaree Gas & Plumbing', 'myaree-gas-plumbing', '(08) 9330 9012', 'contact@myareegas.com.au', '789 Leach Highway, Myaree WA 6154', 'Myaree', 'Dual-licensed gas fitters and plumbers specializing in gas appliance installation and plumbing services for Myaree and surrounding suburbs.', ARRAY['Gas Fitting', 'Appliance Installation', 'Gas Leak Detection', 'Hot Water Systems', 'Cooktop Installation'], 4.7, 85, true, 19, 'PL7654', 'https://myareegas.com.au', '{"Monday": "7:30 AM - 4:30 PM", "Tuesday": "7:30 AM - 4:30 PM", "Wednesday": "7:30 AM - 4:30 PM", "Thursday": "7:30 AM - 4:30 PM", "Friday": "7:30 AM - 4:30 PM", "Saturday": "8:00 AM - 12:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Rapid Response Plumbing', 'rapid-response-plumbing', '(08) 9330 3456', 'urgent@rapidresponse.com.au', '321 Winterfold Road, Myaree WA 6154', 'Myaree', 'Fast response plumbing service with same-day availability. Specializing in urgent repairs and emergency callouts across the southern suburbs.', ARRAY['Emergency Repairs', 'Same Day Service', 'Burst Pipes', 'Hot Water Repairs', 'Toilet Repairs'], 4.8, 143, true, 14, 'PL6543', 'https://rapidresponse.com.au', '{"Monday": "6:00 AM - 8:00 PM", "Tuesday": "6:00 AM - 8:00 PM", "Wednesday": "6:00 AM - 8:00 PM", "Thursday": "6:00 AM - 8:00 PM", "Friday": "6:00 AM - 8:00 PM", "Saturday": "7:00 AM - 6:00 PM", "Sunday": "8:00 AM - 4:00 PM"}', '/placeholder.svg?height=400&width=800'),

('Myaree Maintenance Plumbers', 'myaree-maintenance-plumbers', '(08) 9330 7890', 'info@myareemaintenance.com.au', '654 Kintail Road, Myaree WA 6154', 'Myaree', 'Preventive maintenance specialists helping property owners avoid costly plumbing emergencies through regular inspections and maintenance programs.', ARRAY['Preventive Maintenance', 'Property Inspections', 'Pipe Maintenance', 'Drain Maintenance', 'System Upgrades'], 4.4, 76, false, 21, 'PL5432', 'https://myareemaintenance.com.au', '{"Monday": "8:00 AM - 4:00 PM", "Tuesday": "8:00 AM - 4:00 PM", "Wednesday": "8:00 AM - 4:00 PM", "Thursday": "8:00 AM - 4:00 PM", "Friday": "8:00 AM - 4:00 PM", "Saturday": "Closed", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800'),

('Premium Plumbing Myaree', 'premium-plumbing-myaree', '(08) 9330 2468', 'hello@premiumplumbingmyaree.com.au', '987 South Street, Myaree WA 6154', 'Myaree', 'High-end plumbing services for luxury homes and commercial properties. Attention to detail and premium materials for discerning clients.', ARRAY['Luxury Installations', 'High-End Fixtures', 'Custom Plumbing', 'Designer Bathrooms', 'Commercial Fit-outs'], 4.9, 54, false, 16, 'PL4321', 'https://premiumplumbingmyaree.com.au', '{"Monday": "8:00 AM - 5:00 PM", "Tuesday": "8:00 AM - 5:00 PM", "Wednesday": "8:00 AM - 5:00 PM", "Thursday": "8:00 AM - 5:00 PM", "Friday": "8:00 AM - 5:00 PM", "Saturday": "9:00 AM - 2:00 PM", "Sunday": "Closed"}', '/placeholder.svg?height=400&width=800');
